### ISSUE TITLE
Linux Compiler Error

### ISSUE THREAD

**Issue by semx2a** [gmarcha/pipexMedic#1]
/usr/bin/ld: /tmp/test-b6613a.o:(.bss+0x0): multiple definition of `testDone'; /tmp/main-2d4d36.o:(.bss+0x0): first defined here
/usr/bin/ld: /tmp/runTest-ec7499.o:(.bss+0x0): multiple definition of `testDone'; /tmp/main-2d4d36.o:(.bss+0x0): first defined here
/usr/bin/ld: /tmp/utils-3b73b9.o:(.bss+0x0): multiple definition of `testDone'; /tmp/main-2d4d36.o:(.bss+0x0): first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by gmarcha** [comment]
Hey, I can't reproduce this problem myself, could you give me more information about it ? Thanks!

**Comment by Lucwousin** [comment]
I've got the same issue, both with gcc and clang.

To add:
I'm running Manjaro 5.13.19-2, clang version 13.0.1

**Comment by Lucwousin** [comment]
Adding the extern keyword in front of the definition in main.h fixes this issue

**Comment by gmarcha** [comment]
I'm sorry for the very late answer. :(

I'm aware of this issue but I really don't know why it happens.
You mean that `# define _GNU_SOURCE` is the source of the problem, or did I misunderstood ?

I'm afraid to tell I don't remember why I'm using this, and it's probably not a good idea in this case.
I'll give a try to just add it on macOS, please let me know what happen on your systems.

**Comment by gmarcha** [comment]
No I misunderstood, extern is added in front of the defintion now, please comment if compilation problems continue to happen.
