### ISSUE TITLE
Bash environnement test are wrong

### ISSUE THREAD

**Issue by mariyagd** [gmarcha/pipexMedic#2]
Hello I tried this test on my own computer and on school's computer. The bash output that this tester expect is not at all the bash output I get. So I made my program according to my bash outputs and it's not possible to pass any of these tests.

**Comment by gmarcha** [comment]
Tester has been developed to run on Linux environment with default ubuntu distribution. Other operating systems, distributions or custom shell configurations are not tested and thus not expected to work. Pull-requests are welcome to improve (or simply add) portability.

**Comment by tmazitov** [comment]
Please write the notice in README to prevent new issues with it. I wasted a lot of time on my mac :(

**Comment by gmarcha** [comment]
Noted. I close this issue, feel free to reopen to propose corrections for portability issues.
